version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: go-notes-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:${DB_PORT}"

      

  app:
    build: .
    container_name: go-notes-app
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: ["./go-notes-app"]

  caddy:
    image: caddy:2-alpine
    container_name: go-notes-caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./website:/srv/www/go-notes/website
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - app

volumes:
  db_data: