# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-Notes CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test Go-Notes

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    # Instalar pacotes do sistema necessários para pgx ou outras libs C-based
    - name: Instalar pacotes do sistema
      run: sudo apt update && sudo apt install -y libpq-dev

    - name: Instalar dependências do Go
      run: |
        go mod tidy
        go get ./...

    - name: Compilar aplicação
      run: |
        go build -o go-notes-app .

    - name: Executar testes
      run: |
        go test ./...
